### ISSUE TITLE
Error when clicking email verification link

### ISSUE THREAD

**Issue by Default-01** [devdeck101/authjs-prisma-template#1]
When clicking the verification link in the email, when you get redirected to the site you will get the error message that there is no valid code. but when I try to login afterwards everything works fine and the code did work.

I have looked into what the issue may be, but I'm not sure.

**Comment by devdeck101** [comment]
Thanks Default.

It is not an error. It occur because default npm run dev execution uses react strict Mode which  executes twice the use effect. Once the page load, the token in validated  and clear the token. Then it executes again with no token in the database and generates the error message. In a production build 'npm run build && npm run start' it works fine which is a desired outcome.

Thank for using the project and take the time to make it better .
Bruno (developerdeck101)

**Comment by devdeck101** [comment]
Close with response
